service: members-search-api

frameworkVersion: ">=2.62.0"

plugins:
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    stages:
      - development
  serverless-offline:
    babelOptions:
      presets: ['es2015', 'stage-0']
  webpack:
    packager: 'yarn'
    includeModules: true # enable auto-packing of external modules
provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs14.x
  region: us-west-2
  stage: development
  environment:
    DYNAMODB_MEMBERS_TABLE: members-search-api-${opt:stage, self:provider.stage}-members
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:BatchWriteItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_MEMBERS_TABLE}"

functions:
  export:
    handler: export/handler.handler
    events:
      - schedule:
          rate: rate(5 minutes)   # Testing logs
          #rate: cron(0 8 * * ? *) # 1am PST
          enabled: true
      - http: post /export
    timeout: 60
    package:
      include:
        - '.env'
  graphql:
    handler: graphql/handler.handler
    package:
      include:
        - '.env'
        - 'graphql/schema.graphql'
        - 'graphql/members-schema.graphql'
    events:
      - http:
          method: post
          path: graphql
          cors: true

resources:
  Resources:
    MembersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_MEMBERS_TABLE}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
